[2024-09-09T18:50:28.689+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:50:28.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:50:28.695+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:50:28.694+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:50:28.738+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:50:28.730+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts import getdata
ImportError: cannot import name 'getdata' from 'scripts' (unknown location)
[2024-09-09T18:50:28.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:50:28.842+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.161 seconds
[2024-09-09T18:50:59.374+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:50:59.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:50:59.406+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:50:59.405+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:50:59.448+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:50:59.440+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts import getdata
ImportError: cannot import name 'getdata' from 'scripts' (unknown location)
[2024-09-09T18:50:59.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:50:59.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.184 seconds
[2024-09-09T18:52:25.284+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:52:25.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:52:25.297+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:52:25.296+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:52:25.323+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:52:25.317+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts import getdata
ImportError: cannot import name 'getdata' from 'scripts' (unknown location)
[2024-09-09T18:52:25.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:52:25.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.163 seconds
[2024-09-09T18:52:56.703+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:52:56.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:52:56.767+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:52:56.763+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:52:56.820+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:52:56.810+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts import getdata
ImportError: cannot import name 'getdata' from 'scripts' (unknown location)
[2024-09-09T18:52:56.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:52:57.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.370 seconds
[2024-09-09T18:53:27.760+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:53:27.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:53:27.765+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:53:27.764+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:53:27.796+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:53:27.788+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts import getdata
ImportError: cannot import name 'getdata' from 'scripts' (unknown location)
[2024-09-09T18:53:27.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:53:28.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.922 seconds
[2024-09-09T18:53:59.801+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:53:59.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:53:59.811+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:53:59.811+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:53:59.837+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:53:59.832+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts import getdata
ImportError: cannot import name 'getdata' from 'scripts' (unknown location)
[2024-09-09T18:53:59.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:54:00.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.911 seconds
[2024-09-09T18:54:31.871+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:54:31.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:54:31.876+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:54:31.876+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:54:32.021+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:54:32.014+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:54:32.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:54:32.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.758 seconds
[2024-09-09T18:55:03.630+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:55:03.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:55:03.635+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:55:03.634+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:55:03.656+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:55:03.652+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:55:03.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:55:04.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.850 seconds
[2024-09-09T18:55:34.813+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:55:34.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:55:34.818+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:55:34.817+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:55:34.841+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:55:34.834+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:55:34.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:55:35.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.562 seconds
[2024-09-09T18:56:06.156+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:56:06.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:56:06.159+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:56:06.159+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:56:06.179+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:56:06.175+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:56:06.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:56:06.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.106 seconds
[2024-09-09T18:56:37.206+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:56:37.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:56:37.211+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:56:37.211+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:56:37.234+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:56:37.229+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:56:37.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:56:38.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.637 seconds
[2024-09-09T18:57:09.362+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:09.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:57:09.374+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:57:09.374+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:09.395+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:57:09.390+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:57:09.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:11.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.837 seconds
[2024-09-09T18:57:15.810+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:15.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:57:15.813+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:57:15.813+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:15.849+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:57:15.843+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:57:15.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:16.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.777 seconds
[2024-09-09T18:57:50.572+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:50.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:57:50.578+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:57:50.577+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:50.602+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:57:50.597+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:57:50.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:57:50.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.135 seconds
[2024-09-09T18:58:37.197+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:58:37.198+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:58:37.201+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:58:37.201+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:58:37.221+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:58:37.217+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:58:37.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:58:38.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.045 seconds
[2024-09-09T18:59:09.001+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:59:09.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:59:09.044+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:59:09.044+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:59:09.066+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:59:09.061+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:59:09.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:59:09.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.626 seconds
[2024-09-09T18:59:40.290+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:59:40.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T18:59:40.297+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:59:40.296+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:59:40.318+0000] {logging_mixin.py:190} INFO - [2024-09-09T18:59:40.314+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T18:59:40.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T18:59:40.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.109 seconds
[2024-09-09T19:00:10.738+0000] {processor.py:186} INFO - Started process (PID=61) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:00:10.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:00:10.743+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:00:10.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:00:10.770+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:00:10.764+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T19:00:10.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:00:10.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.203 seconds
[2024-09-09T19:00:41.100+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:00:41.102+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:00:41.104+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:00:41.104+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:00:41.126+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:00:41.122+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T19:00:41.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:00:41.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.396 seconds
[2024-09-09T19:01:13.079+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:01:13.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:01:13.082+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:01:13.082+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:01:13.102+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:01:13.098+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from .scripts import getdata
ImportError: attempted relative import with no known parent package
[2024-09-09T19:01:13.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:01:13.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.837 seconds
[2024-09-09T19:01:28.048+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:01:28.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:01:28.052+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:01:28.052+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:01:28.089+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:01:28.083+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:01:28.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:01:28.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.616 seconds
[2024-09-09T19:02:00.668+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:02:00.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:02:00.673+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:02:00.673+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:02:00.696+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:02:00.692+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:02:00.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:02:01.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.847 seconds
[2024-09-09T19:03:09.702+0000] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:03:09.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:03:09.707+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:03:09.707+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:03:09.731+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:03:09.725+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:03:09.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:03:10.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.675 seconds
[2024-09-09T19:03:40.479+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:03:40.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:03:40.574+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:03:40.573+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:03:40.702+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:03:40.696+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:03:40.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:03:41.979+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.509 seconds
[2024-09-09T19:04:12.937+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:04:12.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:04:12.941+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:04:12.941+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:04:12.962+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:04:12.959+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:04:12.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:04:13.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.268 seconds
[2024-09-09T19:04:44.269+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:04:44.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:04:44.273+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:04:44.273+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:04:44.295+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:04:44.291+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:04:44.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:04:44.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.410 seconds
[2024-09-09T19:05:16.155+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:05:16.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:05:16.161+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:05:16.161+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:05:16.182+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:05:16.177+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:05:16.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:05:16.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.210 seconds
[2024-09-09T19:05:47.125+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:05:47.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:05:47.129+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:05:47.128+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:05:47.151+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:05:47.147+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:05:47.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:05:47.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.116 seconds
[2024-09-09T19:06:18.392+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:06:18.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:06:18.396+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:06:18.395+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:06:18.420+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:06:18.415+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:06:18.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:06:18.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.415 seconds
[2024-09-09T19:06:49.498+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:06:49.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:06:49.516+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:06:49.514+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:06:49.558+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:06:49.550+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:06:49.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:06:49.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.255 seconds
[2024-09-09T19:07:20.056+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:07:20.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:07:20.080+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:07:20.079+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:07:20.140+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:07:20.123+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:07:20.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:07:20.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.483 seconds
[2024-09-09T19:07:53.080+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:07:53.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:07:53.183+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:07:53.182+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:07:53.206+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:07:53.200+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:07:53.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:07:53.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.295 seconds
[2024-09-09T19:08:24.456+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:08:24.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:08:24.461+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:08:24.460+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:08:24.515+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:08:24.507+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:08:24.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:08:24.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.360 seconds
[2024-09-09T19:08:55.256+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:08:55.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:08:55.260+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:08:55.260+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:08:55.280+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:08:55.275+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:08:55.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:08:55.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.196 seconds
[2024-09-09T19:09:25.741+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:09:25.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:09:25.745+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:09:25.744+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:09:25.767+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:09:25.763+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:09:25.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:09:26.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.425 seconds
[2024-09-09T19:09:56.572+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:09:56.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:09:56.575+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:09:56.575+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:09:56.595+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:09:56.591+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:09:56.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:09:56.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.418 seconds
[2024-09-09T19:10:21.138+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:21.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:10:21.142+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:10:21.142+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:21.181+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:10:21.174+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:10:21.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:22.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.401 seconds
[2024-09-09T19:10:52.984+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:52.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:10:53.017+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:10:53.015+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:53.042+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:10:53.034+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:10:53.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:54.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.372 seconds
[2024-09-09T19:10:57.736+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:57.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:10:57.739+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:10:57.739+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:57.777+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:10:57.770+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:10:57.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:10:57.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.157 seconds
[2024-09-09T19:11:28.106+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:11:28.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:11:28.110+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:11:28.110+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:11:28.136+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:11:28.130+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:11:28.138+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:11:28.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.479 seconds
[2024-09-09T19:11:59.413+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:11:59.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:11:59.419+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:11:59.417+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:11:59.444+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:11:59.439+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:11:59.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:11:59.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.479 seconds
[2024-09-09T19:12:30.135+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:12:30.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:12:30.139+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:12:30.139+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:12:30.162+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:12:30.156+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:12:30.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:12:30.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.698 seconds
[2024-09-09T19:13:01.139+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:13:01.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:13:01.143+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:13:01.142+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:13:01.167+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:13:01.163+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:13:01.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:13:01.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.118 seconds
[2024-09-09T19:13:31.429+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:13:31.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:13:31.437+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:13:31.434+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:13:31.478+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:13:31.471+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:13:31.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:13:32.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.148 seconds
[2024-09-09T19:14:02.853+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:14:02.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:14:02.858+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:14:02.858+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:14:02.882+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:14:02.878+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:14:02.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:14:03.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.975 seconds
[2024-09-09T19:14:34.127+0000] {processor.py:186} INFO - Started process (PID=94) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:14:34.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:14:34.131+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:14:34.131+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:14:34.152+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:14:34.148+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:14:34.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:14:34.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.445 seconds
[2024-09-09T19:15:04.912+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:15:04.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:15:04.916+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:15:04.915+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:15:04.940+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:15:04.935+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:15:04.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:15:05.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.784 seconds
[2024-09-09T19:15:35.938+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:15:35.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:15:35.942+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:15:35.941+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:15:35.963+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:15:35.960+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:15:35.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:15:36.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.446 seconds
[2024-09-09T19:16:06.764+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:16:06.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:16:06.767+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:16:06.767+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:16:06.789+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:16:06.784+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:16:06.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:16:06.975+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.218 seconds
[2024-09-09T19:16:37.216+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:16:37.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:16:37.221+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:16:37.221+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:16:37.242+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:16:37.238+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:16:37.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:16:37.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.419 seconds
[2024-09-09T19:17:07.963+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:17:07.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:17:07.967+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:17:07.967+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:17:07.992+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:17:07.987+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:17:07.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:17:08.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.354 seconds
[2024-09-09T19:17:38.466+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:17:38.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:17:38.470+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:17:38.469+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:17:38.491+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:17:38.487+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:17:38.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:17:38.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.395 seconds
[2024-09-09T19:18:09.193+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:18:09.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:18:09.198+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:18:09.197+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:18:09.226+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:18:09.221+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:18:09.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:18:09.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.526 seconds
[2024-09-09T19:18:40.055+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:18:40.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:18:40.060+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:18:40.059+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:18:40.088+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:18:40.082+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:18:40.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:18:40.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.471 seconds
[2024-09-09T19:19:10.882+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:19:10.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:19:10.905+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:19:10.903+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:19:10.959+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:19:10.948+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:19:10.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:19:11.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.515 seconds
[2024-09-09T19:19:41.686+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:19:41.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:19:41.690+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:19:41.690+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:19:41.712+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:19:41.708+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:19:41.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:19:42.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.519 seconds
[2024-09-09T19:20:12.567+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:20:12.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:20:12.572+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:20:12.571+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:20:12.591+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:20:12.587+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:20:12.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:20:13.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.750 seconds
[2024-09-09T19:20:44.080+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:20:44.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:20:44.091+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:20:44.091+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:20:44.124+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:20:44.119+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:20:44.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:20:44.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.598 seconds
[2024-09-09T19:21:15.567+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:21:15.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:21:15.573+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:21:15.572+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:21:15.602+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:21:15.594+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:21:15.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:21:16.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.496 seconds
[2024-09-09T19:21:46.640+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:21:46.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:21:46.648+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:21:46.647+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:21:46.675+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:21:46.670+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:21:46.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:21:47.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.829 seconds
[2024-09-09T19:22:17.846+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:22:18.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:22:18.163+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:22:18.163+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:22:18.187+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:22:18.182+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:22:18.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:22:18.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.457 seconds
[2024-09-09T19:22:49.262+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:22:49.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:22:49.266+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:22:49.266+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:22:49.289+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:22:49.285+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:22:49.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:22:50.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.907 seconds
[2024-09-09T19:23:20.480+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:23:20.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:23:20.484+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:23:20.484+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:23:20.510+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:23:20.504+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:23:20.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:23:21.029+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.567 seconds
[2024-09-09T19:23:51.640+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:23:51.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:23:51.644+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:23:51.643+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:23:51.665+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:23:51.662+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:23:51.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:23:51.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.138 seconds
[2024-09-09T19:24:22.245+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:24:22.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:24:22.250+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:24:22.249+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:24:22.276+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:24:22.271+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:24:22.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:24:23.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.165 seconds
[2024-09-09T19:24:53.609+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:24:53.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:24:53.614+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:24:53.614+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:24:53.655+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:24:53.648+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:24:53.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:24:54.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.445 seconds
[2024-09-09T19:25:24.237+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:25:24.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:25:24.241+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:25:24.241+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:25:24.266+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:25:24.261+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:25:24.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:25:24.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.195 seconds
[2024-09-09T19:25:54.697+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:25:54.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:25:54.702+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:25:54.701+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:25:54.724+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:25:54.720+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:25:54.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:25:54.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.116 seconds
[2024-09-09T19:26:26.067+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:26:26.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:26:26.072+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:26:26.071+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:26:26.094+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:26:26.090+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:26:26.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:26:27.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.124 seconds
[2024-09-09T19:26:57.665+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:26:57.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:26:57.669+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:26:57.668+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:26:57.694+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:26:57.689+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:26:57.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:26:58.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.373 seconds
[2024-09-09T19:27:29.085+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:27:29.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:27:29.088+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:27:29.088+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:27:29.126+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:27:29.116+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:27:29.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:27:30.482+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.403 seconds
[2024-09-09T19:28:00.967+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:28:00.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:28:00.972+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:28:00.971+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:28:00.995+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:28:00.991+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:28:00.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:28:01.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.422 seconds
[2024-09-09T19:28:31.866+0000] {processor.py:186} INFO - Started process (PID=121) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:28:31.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:28:31.872+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:28:31.872+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:28:31.897+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:28:31.892+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:28:31.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:28:32.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.823 seconds
[2024-09-09T19:29:03.252+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:29:03.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:29:03.256+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:29:03.256+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:29:03.278+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:29:03.274+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:29:03.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:29:03.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.119 seconds
[2024-09-09T19:29:33.591+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:29:33.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:29:33.595+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:29:33.595+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:29:33.618+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:29:33.614+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 6, in <module>
    from scripts.hdfs_pipeline import getdata
ModuleNotFoundError: No module named 'scripts.hdfs_pipeline'
[2024-09-09T19:29:33.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:29:34.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.430 seconds
[2024-09-09T19:30:02.488+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:02.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:30:02.491+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:30:02.491+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:02.527+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:30:02.520+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:30:02.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:03.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.855 seconds
[2024-09-09T19:30:34.335+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:34.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:30:34.339+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:30:34.339+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:34.361+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:30:34.358+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:30:34.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:34.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.193 seconds
[2024-09-09T19:30:53.589+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:53.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:30:53.592+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:30:53.592+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:53.628+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:30:53.622+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:30:53.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:30:54.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.404 seconds
[2024-09-09T19:31:25.285+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:31:25.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:31:25.289+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:31:25.289+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:31:25.310+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:31:25.306+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:31:25.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:31:26.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.782 seconds
[2024-09-09T19:31:56.392+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:31:56.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:31:56.395+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:31:56.395+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:31:56.422+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:31:56.416+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:31:56.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:31:57.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.854 seconds
[2024-09-09T19:32:27.993+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:32:27.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:32:27.996+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:32:27.996+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:32:28.023+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:32:28.017+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:32:28.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:32:28.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.455 seconds
[2024-09-09T19:32:58.835+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:32:58.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:32:58.839+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:32:58.838+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:32:58.860+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:32:58.856+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:32:58.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:32:59.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.852 seconds
[2024-09-09T19:33:29.790+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:33:29.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:33:29.794+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:33:29.793+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:33:29.815+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:33:29.812+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:33:29.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:33:30.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.520 seconds
[2024-09-09T19:34:00.452+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:34:00.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:34:00.457+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:34:00.457+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:34:00.480+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:34:00.475+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:34:00.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:34:00.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.215 seconds
[2024-09-09T19:34:30.796+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:34:30.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T19:34:30.799+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:34:30.799+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:34:30.825+0000] {logging_mixin.py:190} INFO - [2024-09-09T19:34:30.819+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 7, in <module>
    from pyspark.sql import SparkSession;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pyspark'
[2024-09-09T19:34:30.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T19:34:31.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.455 seconds
[2024-09-09T20:10:20.813+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:10:20.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:10:20.831+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:10:20.830+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:10:20.971+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:10:20.963+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 17, in <module>
    "retry_delay": timedelta(minute=2)
                   ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-09-09T20:10:20.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:10:21.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.286 seconds
[2024-09-09T20:10:52.734+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:10:52.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:10:52.812+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:10:52.810+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:10:53.173+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:10:53.162+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 17, in <module>
    "retry_delay": timedelta(minute=2)
                   ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-09-09T20:10:53.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:10:53.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.712 seconds
[2024-09-09T20:11:24.085+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:11:24.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:11:24.183+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:11:24.182+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:11:24.342+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:11:24.335+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 17, in <module>
    "retry_delay": timedelta(minute=2)
                   ^^^^^^^^^^^^^^^^^^^
TypeError: 'minute' is an invalid keyword argument for __new__()
[2024-09-09T20:11:24.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:11:24.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.414 seconds
[2024-09-09T20:11:29.842+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:11:29.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:11:29.846+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:11:29.846+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:11:29.951+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:11:29.943+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 24, in intiate_spark
    .appname("pipeline")\
     ^^^^^^^
AttributeError: 'Builder' object has no attribute 'appname'. Did you mean: 'appName'?
[2024-09-09T20:11:29.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:11:30.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.724 seconds
[2024-09-09T20:12:00.764+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:00.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:12:00.771+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:12:00.769+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:00.988+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:12:00.980+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 24, in intiate_spark
    .appname("pipeline")\
     ^^^^^^^
AttributeError: 'Builder' object has no attribute 'appname'. Did you mean: 'appName'?
[2024-09-09T20:12:00.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:02.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.386 seconds
[2024-09-09T20:12:04.259+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:04.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:12:04.263+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:12:04.263+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:04.513+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:12:04.507+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 25, in intiate_spark
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-09-09T20:12:04.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:04.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.590 seconds
[2024-09-09T20:12:36.247+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:36.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:12:36.252+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:12:36.252+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:36.475+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:12:36.471+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 25, in intiate_spark
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-09-09T20:12:36.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:12:37.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.379 seconds
[2024-09-09T20:13:09.753+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:13:09.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:13:09.757+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:13:09.757+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:13:09.998+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:13:09.994+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 25, in intiate_spark
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-09-09T20:13:09.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:13:10.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.966 seconds
[2024-09-09T20:13:40.961+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:13:40.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:13:40.965+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:13:40.965+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:13:41.193+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:13:41.188+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 25, in intiate_spark
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-09-09T20:13:41.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:13:41.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 0.410 seconds
[2024-09-09T20:14:11.740+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:14:11.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:14:11.746+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:14:11.745+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:14:11.971+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:14:11.967+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 25, in intiate_spark
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-09-09T20:14:11.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:14:12.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.020 seconds
[2024-09-09T20:14:43.625+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:14:43.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/HDFS_pipeline_DAG.py for tasks to queue
[2024-09-09T20:14:43.630+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:14:43.628+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:14:43.925+0000] {logging_mixin.py:190} INFO - [2024-09-09T20:14:43.920+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/HDFS_pipeline_DAG.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 28, in <module>
    spark = intiate_spark()
            ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/HDFS_pipeline_DAG.py", line 25, in intiate_spark
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-09-09T20:14:43.926+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/HDFS_pipeline_DAG.py
[2024-09-09T20:14:45.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/HDFS_pipeline_DAG.py took 1.975 seconds
